---
# Ekvivalent k prikazu:
# ansible all -m apt -a "name=apache2 state=latest" --become --ask-become-pass
- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: apache2
